### ISSUE TITLE
Make all fundamental stats configurable

### ISSUE THREAD

**Issue by EtiTheSpirit** [dgosling/RoR2-Samus#11]
This is not usually super tedious to implement (in my own experience, writing the descriptions of the config items was harder than implementing the configs themselves), but I believe that the mod would benefit from all of its fundamental stats being configurable. This is something I do in my own mod releases so that users may customize the character to best fit their playstyle and, if they have made one, their modpack.

Implementing this change would provide a way to avoid situations like #9 for even the most otherworldly of edge cases, as users will just be able to edit that value on their own rather than relying on you to implement or tweak it at your convenience.

The stats I suggest *at the very least* (and what constitutes "fundamental stats") are as follows:
* Base damage + Leveled damage
* Damage factors for all attacks (applies to power beam and its charge (and, if you add #8, charge beam's blast damage), both missiles, and both bombs. Each has its own stat, and applies to the base damage multiplicatively)
* Base movement speed
* Base armor
* Base crit chance (implementation note: this is actually an int between 0 and 100, not a float like typical percents, just to save you some time)

There's a lot more stats and if you have a wild hair and time to burn, you can add basically everything as a config, but the ones listed above are the fundamentals that I think are necessary for a flexible experience for all players.

**Comment by dgosling** [comment]
I have created an update and pushed it to github, I just need to do a bit of testing tomorrow and if everything is good, I'll upload the new version to thunderstore that includes this enhancement.

**Comment by dgosling** [comment]
I have uploaded a new update with configurable stats.

**Comment by EtiTheSpirit** [comment]
Did some playtesting with it and everything seems to work as intended. The update satisfies the feature request. Thanks!
