### ISSUE TITLE
Not Loading?

### ISSUE THREAD

**Issue by KitBallard64** [dgosling/RoR2-Samus#3]
Finally got around to trying this but seems I'm either doing som'in wrong, or this hasn't been set up for the newest update. So uhm... yeah... It's not loading for me... Hope it's just a "needs to be updated" and "be patient" kind of situation. Which I can~♪

~Kito

**Comment by dgosling** [comment]
Just needs to be updated. I plan on working on updating it tomorrow since most of the things I've been waiting on have been updated.

**Comment by KitBallard64** [comment]
Ah ok! Thank you ^_^ Sorry to of bothered ya. Good luck!

~Kito

**Comment by dgosling** [comment]
Finally finished the update and got it uploaded!

**Comment by KitBallard64** [comment]
Oh! Thank you. I appreciate you saying som'in here, even if you didn't need too~♪ I'll prob try to check it out tomorrow! Good luck out there and keep it cool ^_^

~Kito
