### ISSUE TITLE
ICBM Synergy?

### ISSUE THREAD

**Issue by KitBallard64** [dgosling/RoR2-Samus#4]
A fun little idea me and my gf was talking about is the Pocket ICBM and Samus' missiles. Would that be a possible? I do know the Engie's spears can go triple, so it's possible as an idea already. Unless you think it'd be a bit _too_ strong, then I'd understand. Either way, thank you again for the wonderful work!

~Kito

**Comment by dgosling** [comment]
I can see about adding that tomorrow.

**Comment by KitBallard64** [comment]
Oh, neat! I appreciate the thought ^_^ No rush, of course, as it was a silly musing we had.

~Kito

**Comment by dgosling** [comment]
No problem, that was something I forgot about adding so you just reminded me. Although it will have to wait a bit since it seems like there's some kind of bug with multiplayer and Samus not spawning in that I need to figure out first.

**Comment by KitBallard64** [comment]
No rush again ^_^ Glad we spurred you into reminding you haha XD Good luck, mate =3

~Kito

**Comment by dgosling** [comment]
Finally got around to adding and uploading the update that adds this. Enjoy!
