### ISSUE TITLE
Gasoline causes stuttering/freezing

### ISSUE THREAD

**Issue by elladunbar** [dgosling/RoR2-Samus#7]
Basically the title. With at least 1 gasoline and when killing large amounts of enemies at once (easiest to do with the super bomb in morph ball mode), the game will freeze for a few moments or longer depending on number of kills. Will-o'-the-wisp did not cause the same issue when I tested it leading me to believe that something about all the burning debuffs being applied from gasoline is what's causing it. The issue seemed slightly worse when other mods were enabled, but still persisted when only Samus and it's dependencies were enabled. 

**Specs:**

- GTX 1070 (overclocked)
- i5-8600k
- more things I can list but probably aren't relevant

**Full Mod List (when enabled):**

- BepInExPack
- BetterUI
- ChefMod
- DebugToolkit
- dgoslings_Samus_Mod
- Goku
- HookGenPatcher
- KingModUtilities
- Phoenix_Wright_Mod
- R2API
- ScrollableLobbyUI
- TF2SoldierMod
- Tracer
- VRAPI

Overall, mostly mods that don't affect gameplay, just survivors and some QOL improvements. Also, I hope we can get to the bottom of this, so let me know what other info, if any, you need! I really love the mod and enjoy playing Samus when I can :)

**Comment by dgosling** [comment]
I went ahead and quickly fixed it since I've been meaning to for a while. It doesn't seem to freeze at all anymore. I also was able to fix the ragdoll too. I've uploaded the update and it should appear after thunderstore refreshes its cache.

**Comment by elladunbar** [comment]
Works like a charm. Thank you!
