### ISSUE TITLE
Damage scaling way to low

### ISSUE THREAD

**Issue by Superdouper** [dgosling/RoR2-Samus#9]
Its 0.3 per level compared to other survivors having about 2.4 per level. I just fix it with aerolt and she's actually able to kill things at later stages. Her health scaling is also a little high in comparison but that doesn't really matter. Great mod though, her movement feels very nice.

**Comment by dgosling** [comment]
I never noticed that. The damage scaling was based on Paladin's damage scaling since I initially based the code off that. I'll probably increase it in a future update. Thanks for the heads up!

**Comment by neochiken** [comment]
Excited for this as this mod is the best VR Metroid game

**Comment by dgosling** [comment]
I have created an update and pushed it to github, I just need to do a bit of testing tomorrow and if everything is good, I'll upload the new version to thunderstore that includes this fix.

**Comment by dgosling** [comment]
I have just released an update that should fix this and set it to 2 per level. I also implemented #11 so you can easily change it.
